#!/usr/bin/env bash
# Vendors the four OFL faces into apps/web/public/fonts.
#
# Run once on a machine with network access, then commit the .woff2 files (or bake this
# into the image build). The application must never fetch a font at runtime: COEP
# require-corp blocks it silently, and scripts/check-determinism.sh fails the build on
# an external URL in the bundle.
set -euo pipefail

DEST="$(dirname "$0")/../apps/web/public/fonts"
mkdir -p "$DEST"

fetch() {
  local name="$1" url="$2"
  if [ -f "$DEST/$name" ]; then
    echo "have    $name"
    return
  fi
  echo "fetch   $name"
  curl -fsSL "$url" -o "$DEST/$name"
}

INTER="https://github.com/rsms/inter/raw/v4.0/docs/font-files"
fetch "Inter-Regular.woff2"      "$INTER/Inter-Regular.woff2"
fetch "Inter-Medium.woff2"       "$INTER/Inter-Medium.woff2"
fetch "InterTight-ExtraBold.woff2" "$INTER/InterDisplay-ExtraBold.woff2"

JETBRAINS="https://github.com/JetBrains/JetBrainsMono/raw/master/fonts/webfonts"
fetch "JetBrainsMono-Regular.woff2" "$JETBRAINS/JetBrainsMono-Regular.woff2"
fetch "JetBrainsMono-Medium.woff2"  "$JETBRAINS/JetBrainsMono-Medium.woff2"

ATKINSON="https://github.com/googlefonts/atkinson-hyperlegible/raw/main/fonts/webfonts"
fetch "AtkinsonHyperlegible-Regular.woff2" "$ATKINSON/Atkinson-Hyperlegible-Regular-102a.woff2"

cat > "$DEST/fonts.css" <<'CSS'
/* Generated by scripts/fetch-fonts.sh. Imported by index.html when present. */
@font-face { font-family: "Inter"; src: url("/fonts/Inter-Regular.woff2") format("woff2"); font-weight: 400; font-display: swap; }
@font-face { font-family: "Inter"; src: url("/fonts/Inter-Medium.woff2") format("woff2"); font-weight: 500; font-display: swap; }
@font-face { font-family: "Inter Tight"; src: url("/fonts/InterTight-ExtraBold.woff2") format("woff2"); font-weight: 800; font-display: swap; }
@font-face { font-family: "JetBrains Mono"; src: url("/fonts/JetBrainsMono-Regular.woff2") format("woff2"); font-weight: 400; font-display: swap; }
@font-face { font-family: "JetBrains Mono"; src: url("/fonts/JetBrainsMono-Medium.woff2") format("woff2"); font-weight: 500; font-display: swap; }
@font-face { font-family: "Atkinson Hyperlegible"; src: url("/fonts/AtkinsonHyperlegible-Regular.woff2") format("woff2"); font-weight: 400; font-display: swap; }
CSS

echo "done — fonts in $DEST"
